name: hierarchicalforecast
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numpy
  - numba
  - pandas
  - scikit-learn
  - statsmodels
  - pip
  - pip:
    - nbdev
    - mycolorpy
    - quadprog
